#!/usr/bin/env php -ddisplay_errors=on
<?php
include("../config.php");
include("../lib/lib.php");

session_start();
foreach ($GLOBALS["apcids"] as $prise => $ip) {
  getPDU($prise);
  for ($i=1; $i < 25; $i++) {
    if (preg_match("/baie/",$_SESSION[$prise]["names"][$i])) {
      print("$prise/$i: ".$_SESSION[$prise]["names"][$i]."\n");
    }
  }
}
